### ISSUE TITLE
Code release

### ISSUE THREAD

**Issue by cascat0** [BCV-Uniandes/MuST#1]
Great work! Looking forward to open source code.

November 30th is only 10 days away, hahaha.

**Comment by cascat0** [comment]
And I have a question.

In the paper, you mentioned that "Multiple surgical workflow analysis models like OperA [5], SAHC [7], and Trans-SVNet [11] incorporated Transformer layers to TCNs in order to efficiently combine the spatial and temporal features. Nonetheless, their dependence on TCN modeling leads to a loss of finer-grained information, and using temporalagnostic backbones limits frame embeddings to capture only spatial information."

Why does TCN modeling lose fine-grained information? I'm a little confused about this.

**Comment by aperezr20** [comment]
Hello! Thank you for your interest in our work.

We're releasing the code this week. Regarding your question, dilated convolutions use increasing dilation factors in the temporal dimension to expand the receptive field, which is great for capturing long-term dependencies, but can limit the model's ability to capture short-term patterns or fine-grained transitions.
